# Generated by Django 3.0.4 on 2020-03-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='CityName', max_length=200)),
                ('population', models.IntegerField(db_column='Population')),
                ('zipcode', models.IntegerField(db_column='Zip')),
                ('state', models.CharField(db_column='State', max_length=20)),
                ('lat', models.FloatField(db_column='Latitude')),
                ('lon', models.FloatField(db_column='Longitude')),
            ],
        ),
    ]
